/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./theme.ts"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        backdrop: "rgba(27, 28, 25, 0.45)",
        background: "#fbf9f4",
        surface: "#fbf9f4",
        "surface-dim": "#dbdad5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-variant": "#e4e2dd",
        "on-background": "#1b1c19",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#54433c",
        primary: "#823b18",
        "on-primary": "#ffffff",
        "primary-container": "#a0522d",
        "on-primary-container": "#ffe1d6",
        secondary: "#904d00",
        "on-secondary": "#ffffff",
        outline: "#87736b",
        "outline-variant": "#dac1b8",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        destructive: "#ba1a1a",
        "destructive-foreground": "#ffffff",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
      },
      fontFamily: {
        display: ["Newsreader_400Regular"],
        "display-italic": ["Newsreader_400Regular_Italic"],
        "display-semibold": ["Newsreader_600SemiBold"],
        body: ["Manrope_400Regular"],
        "body-medium": ["Manrope_500Medium"],
        "body-bold": ["Manrope_700Bold"],
        label: ["Manrope_500Medium"],
      },
      borderRadius: {
        sm: "8px",
        DEFAULT: "12px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "32px",
      },
    },
  },
  plugins: [],
};
